### ISSUE TITLE
Makefile error (kernel/GNUmakefile:21)

### ISSUE THREAD

**Issue by Cr0a3** [limine-bootloader/limine-rust-barebones#7]
When I try to build the template (i just run `make`), i get following error message:
```
cp target/x86_64-unknown-none/debug/$(cd target/x86_64-unknown-none/debug/ && find -maxdepth 1 -perm -111 -type f)  kernel
cp: target 'kernel' is not a directory
```
Which is line 21 in `kernel/GNUmakefile`

Thx for an answer

**Comment by Mintsuki** [comment]
Do you have findutils installed?

**Comment by Cr0a3** [comment]
yes:
```
sudo apt-get install findutils
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
findutils is already the newest version (4.8.0-1ubuntu3).
The following packages were automatically installed and are no longer required:
  libstd-rust-1.66 libstd-rust-1.70
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by Mintsuki** [comment]
I cannot reproduce this issue, not even in an Ubuntu Docker container...

Can you provide more details about your host system, which Rust version are you using and where you got it from?

Also I cannot help but notice that there are slight differences between the actual line 21 of the makefile and the terminal output you have provided initially. Is this some manual copy paste mistake or have you made more changes to the makefiles/build system than you described?

**Comment by Cr0a3** [comment]
I use Windows Subsystem for Linux (WSL) in there is Ubuntu. The Windows-Build is the newest Insider Build of Windows 11. My CPU ist a Ryzen 5 5600 (so it is x64). 
What I rember now is i pastet a slash in the cd part after the rust target. (In the case of the example debug). I removed it now and i get the same error:
```
cp target/x86_64-unknown-none/debug/$(cd target/x86_64-unknown-none/debug && find -maxdepth 1 -perm -111 -type f) kernel
cp: target 'kernel' is not a directory
```

**Comment by Cr0a3** [comment]
@mintsuki

**Comment by jasondyoungberg** [comment]
I'm also getting this same error, how did you fix it?

**Comment by jasondyoungberg** [comment]
I got it working by using wsl's file system instead of window's (using ~ instead of /mnt/c).

**Comment by Cr0a3** [comment]
Thanks, the fix also works for me

**Comment by lylythechosenone** [comment]
@Toni-Graphics @jasondyoungberg is this still an issue with the makefile, or was it user error?

**Comment by jasondyoungberg** [comment]
It's kinda both? The command doesn't work if are using it on the windows filesystem instead of linux's.

**Comment by Cr0a3** [comment]
yeah, both. Maybe point it out in the readme, that you need to use ~ instead of /mnt/c in WSL
